### ISSUE TITLE
Add live stream vframe function

### ISSUE THREAD

**Issue by leauge7** [pili-engineering/pili-sdk-nodejs#28]
exports.streamVframe = function(mac, streamId, name, format, width, height, rotate, timestamp, options, fn) {
  var path = '/streams/' + streamId + '/vframe';
  var data = {};

  data['name'] = name;
  data['format'] = format;
  data['w'] = width;
  data['h'] = height;
  data['timestamp'] = timestamp;
  data['rotate'] = rotate;
  
  if (options) {
    if (options.notifyUrl) {
      data['notifyUrl'] = options.notifyUrl;
    }
  }

  API.request.post(mac, path, data, function(err, responseData) {
    if (err) {
      fn(err, null);
    } else {
      fn(null, responseData);
    }
  });
}

**Comment by 0dayZh** [comment]
感谢，我们会考虑在后续版本做支持。

**Comment by leauge7** [comment]
^_^
