### ISSUE TITLE
Pili.publishURL 的最后一个参数expireAfterSec是不是没用

### ISSUE THREAD

**Issue by sunkuo** [pili-engineering/pili-sdk-nodejs#51]
exports.publishURL = function(credentials, domain, hub, key, expireAfterSec) {

	var expire = Math.floor(Date.now()/1000);
	var path = fmt.format('/%s/%s?e=%d', hub, key, expire);
	var token = credentials.sign(path);
	return fmt.format('rtmp://%s%s&token=%s', domain, path, token);
}

在代码里，expireAfterSec并没有用到呀？

**Comment by longbai** [comment]
多谢指出，已经修正。
